# Icarus Trading System Configuration

# Database Configuration
database:
  host: ${TIGER_HOST}
  port: ${TIGER_PORT:5432}
  database: ${TIGER_DATABASE:tsdb}
  user: ${TIGER_USER:tsdbadmin}
  password: ${TIGER_PASSWORD}
  pool_min_size: 5
  pool_max_size: 20
  timeout: 30

# Tiger Cloud Configuration
tiger:
  service_id: ${TIGER_SERVICE_ID}
  max_concurrent_forks: 10

# Trading Configuration
trading:
  mode: paper  # paper or real - DEFAULT TO PAPER
  initial_capital: 10000
  position_size_pct: 20  # % of allocated capital per trade
  position_exit_pct: 50  # % of position to exit on sell signal
  symbols:
    - BTCUSDT
    - ETHUSDT

# Binance API Configuration
binance:
  api_key: ${BINANCE_API_KEY:}  # Set via environment variable
  api_secret: ${BINANCE_API_SECRET:}  # Set via environment variable
  testnet: true  # ALWAYS START WITH TESTNET
  testnet_url: "https://testnet.binance.vision"

# Slippage simulation for paper trading
slippage:
  enabled: true
  percentage: 0.1  # 0.1% = 10 basis points

# Risk Configuration
risk:
  max_position_size_pct: 20  # % of allocated capital
  max_daily_loss_pct: 5      # % of total portfolio
  max_exposure_pct: 80       # % of portfolio
  max_strategy_drawdown_pct: 10

# Strategy Configuration
strategies:
  momentum:
    enabled: true
    symbol: BTCUSDT
    ma_short: 20
    ma_long: 50
    warmup_period: 50

  macd:
    enabled: true
    symbol: BTCUSDT
    fast_period: 12
    slow_period: 26
    signal_period: 9
    warmup_period: 50

# Meta-Strategy Configuration
meta_strategy:
  evaluation_interval_minutes: 5  # Changed from hours to minutes for frequent fork demos
  initial_allocation: equal  # equal or custom

# Fork Usage Configuration
fork_usage:
  # Strategy validation intervals (per strategy)
  validation_interval_minutes: 5  # Each strategy validates every 5 minutes

  # Parameter optimization intervals
  optimization_interval_minutes: 15  # Test new parameters every 15 minutes

  # Meta-strategy scenario testing
  scenario_analysis_enabled: true  # Test allocation scenarios on every rebalance

  # Fork lifecycle settings
  default_fork_ttl_seconds: 600  # 10 minutes (shorter for frequent creation)
  validation_fork_ttl_seconds: 300  # 5 minutes for quick validations
  cleanup_check_interval_seconds: 60  # Check for expired forks every minute

# Logging Configuration
logging:
  level: INFO
  format: json
  file: logs/icarus.log
